### ISSUE TITLE
read_only flag

### ISSUE THREAD

**Issue by a-sevin** [milk-org/ImageStreamIO#10]
I would like to add a read_only flag to prevent a publisher to modify the SHM (essentially for debuging a module when the system is running).
good idea ?

**Comment by oguyon** [comment]
Yes this is a good idea.
How would you do that ? If the flag is in the image stream, how does it prevent SOME processes from writing ?

**Comment by a-sevin** [comment]
At the low level, at this time, nothing (I don't know if you can modify permission on the file descriptor on the fly).
At the user level, we have our abstraction layer called Octopus which can verify the flag before writing any thing.
Arnaud

**Comment by oguyon** [comment]
OK, so the application/client is responsible for checking the flag before writing. This is quite useful.
How about we make it a uint64 flag to potentially enable more fine-grained permission flags in the future ?
Adding a new field in the stream structure will have to be deployed carefully as it will bot be backward-compatible - that's why I suggest we give ourselves room for future features with 64 bits/flags.

**Comment by a-sevin** [comment]
It makes sense! I agree
