### ISSUE TITLE
add timestamp and frame number for each slice in buffer 

### ISSUE THREAD

**Issue by jaredmales** [milk-org/ImageStreamIO#5]
Could we add an array of timespecs and maybe frame numbers, each with the same size as size[2] (the third dimension)?  Something like:
timespec * timestamp;
uint64_t * frame_no;

Then when the image is created:
timestamp = (timespec *) malloc(sizeof(timespec)*size[2]);
frame_no = (uint64_t *) malloc(sizeof(uint64_t)*size[2]);

Then each slice would have a corresponding timestamp and frame number.  So when you update image cnt1, you also update its timestamp and frame_no.

**Comment by a-sevin** [comment]
In addition, it will be useful to know where the subscriber writes. 2 ways:

1. use the value of *write* (low cost solution)
2. define write as a vector of size[2] elements (I prefer this one)

In the case of circular buffer, it could be useful to lock a buffer (when the reader is slower than the writer) to prevent memory corruption. But I think there are standard mechanisms to do that efficiently.

**Comment by a-sevin** [comment]
I need to implement it, I will do it on the beta branch. 
In this branch, I'll also push the GPUIPC feature inside.

**Comment by oguyon** [comment]
Something like that exists in AOloopControl module. Look at AOloopControl_RTstreamLOG.c
This was done to optimize data logging timing accuracy and resources use. The process writing the data creates two small circular buffers (in shared memory) and write frames into them, along with time stamps. Then, a small non-real-time process can collect and package these for data logging on disk.

This is a very useful way to log data without requiring many processes and without requiring real-time performance on lots of processes. It would be great to promote this to become a standard feature of milk instead of keeping it buried deep in cacao.

I use it extensively to log SCExAO data. It works great and takes very little resources.

**Comment by jaredmales** [comment]
I have implemented something similar in MagAO-X.  The "stream writer" is just a separate thread in the "frame grabber" process, with an independently settable RT priority.  Same concept, dumps to a simple binary file with minimal meta data assuming you can reconstruct a full FITS-type header from the timestamp.  

I'm experimenting with on-the-fly compression with LZ4, looks like it can keep up (compress 1 sec of data in < 1 sec) and get ~75% compression ratio.

What if we switch to an array of `void *` to `structs` to replace both the keyword system and the timestamp per cube-plane problem?  You could then define a struct to hold whatever RT metadata you need, and ImageStreamIO wouldn't know about the internals other than the `sizeof`.

**Comment by oguyon** [comment]
75% compression ratio at the cost of a significant fraction of a CPU core doesn't seem worth it. I have similar (not very positive) experience with compression. And then, when we need to process data, it also needs to be expanded, taking more CPU resource. It becomes hard in practice to support post-processing with compressed files. Anyway... that is just my opinion. It's a good thing to enable a compression feature/option and leave it up to the user to use it or not.

The "stream writer" you describe is (I think) similar to the "logshim / logshimon / logshimoff / logshimstat" scripts we have in CommandLineInterface/scripts. Very useful, but requires one thread per stream you save, and there are real-time requirements on that thread so it doesn't miss frames. When working on a busy systems with potentially ~100 streams to save at >kHz, this becomes very hard to manage. That's why I suggest we develop a standard way for the process that is writing to the stream to also hold a couple of small circular buffers so that the logging process can grab larger time chunks without having to respond fast.

**Comment by jaredmales** [comment]
Right, I have a circular buffer (each slice is just a `timespec` and the
image data) being filled up by the frame grabber (or whatever producer).
The stream writer is just waiting for a signal that a chunk of the circular
buffer is full and then it writes out that chunk (i.e. 100 MB at a time).
That's 1 sec of PyWFS frames, so the writer just has to be able to write
100 MB in < 1 sec, which isn't a hard real time requirement in any way.

**Comment by oguyon** [comment]
OK - that's a good approach. Sorry I misunderstood.
One single circular buffer is a better way than the two circular buffers I coded: the process that "collects" data can get to it whenever it wants as opposed to getting data when one of the two buffers is full.

We should think about standardizing this so that processes can easily enable this data logging. That's what I tried to do in AOloopControl_RTstreamLOG (look at function prototypes in .h file). Will think about making it more general, and also using a single circular buffer instead of two.
